spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/famly   # ← not "db"
    username: ${POSTGRES_USER:famly}
    password: ${POSTGRES_PASSWORD:famly}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
